
import { ACTIONS_PREFIX } from '../constants';

export const PREFIX = `${ACTIONS_PREFIX}BILL_TYPE__`;

export const COLLECTION_FETCH = `${PREFIX}COLLECTION_FETCH`;
export const COLLECTION_FETCH_SUCCESS = `${PREFIX}COLLECTION_FETCH_SUCCESS`;
export const COLLECTION_FETCH_FAILURE = `${PREFIX}COLLECTION_FETCH_FAILURE`;

export const SINGLE_ADD = `${PREFIX}SINGLE_ADD`;
export const SINGLE_ADD_SUCCESS = `${PREFIX}SINGLE_ADD_SUCCESS`;
export const SINGLE_ADD_FAILURE = `${PREFIX}SINGLE_ADD_FAILURE`;

export const SINGLE_FETCH = `${PREFIX}SINGLE_FETCH`;
export const SINGLE_FETCH_SUCCESS = `${PREFIX}SINGLE_FETCH_SUCCESS`;
export const SINGLE_FETCH_FAILURE = `${PREFIX}SINGLE_FETCH_FAILURE`;

export const SINGLE_UPDATE = `${PREFIX}SINGLE_UPDATE`;
export const SINGLE_UPDATE_SUCCESS = `${PREFIX}SINGLE_UPDATE_SUCCESS`;
export const SINGLE_UPDATE_FAILURE = `${PREFIX}SINGLE_UPDATE_FAILURE`;
